/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DarkovyPoukazRouteImport } from './routes/darkovy-poukaz'
import { Route as OchranaOsobnichUdajuGdprRouteImport } from './routes/ochrana-osobnich-udaju-gdpr'
import { Route as PredNavstevouRouteImport } from './routes/pred-navstevou'
import { Route as VseobecneObchodniPodminkyRouteImport } from './routes/vseobecne-obchodni-podminky'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkovyPoukazRoute = DarkovyPoukazRouteImport.update({
  id: '/darkovy-poukaz',
  path: '/darkovy-poukaz',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaOsobnichUdajuGdprRoute =
  OchranaOsobnichUdajuGdprRouteImport.update({
    id: '/ochrana-osobnich-udaju-gdpr',
    path: '/ochrana-osobnich-udaju-gdpr',
    getParentRoute: () => rootRouteImport,
  } as any)
const PredNavstevouRoute = PredNavstevouRouteImport.update({
  id: '/pred-navstevou',
  path: '/pred-navstevou',
  getParentRoute: () => rootRouteImport,
} as any)
const VseobecneObchodniPodminkyRoute =
  VseobecneObchodniPodminkyRouteImport.update({
    id: '/vseobecne-obchodni-podminky',
    path: '/vseobecne-obchodni-podminky',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/darkovy-poukaz': typeof DarkovyPoukazRoute
  '/ochrana-osobnich-udaju-gdpr': typeof OchranaOsobnichUdajuGdprRoute
  '/pred-navstevou': typeof PredNavstevouRoute
  '/vseobecne-obchodni-podminky': typeof VseobecneObchodniPodminkyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/darkovy-poukaz': typeof DarkovyPoukazRoute
  '/ochrana-osobnich-udaju-gdpr': typeof OchranaOsobnichUdajuGdprRoute
  '/pred-navstevou': typeof PredNavstevouRoute
  '/vseobecne-obchodni-podminky': typeof VseobecneObchodniPodminkyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/darkovy-poukaz': typeof DarkovyPoukazRoute
  '/ochrana-osobnich-udaju-gdpr': typeof OchranaOsobnichUdajuGdprRoute
  '/pred-navstevou': typeof PredNavstevouRoute
  '/vseobecne-obchodni-podminky': typeof VseobecneObchodniPodminkyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/darkovy-poukaz'
    | '/ochrana-osobnich-udaju-gdpr'
    | '/pred-navstevou'
    | '/vseobecne-obchodni-podminky'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/darkovy-poukaz'
    | '/ochrana-osobnich-udaju-gdpr'
    | '/pred-navstevou'
    | '/vseobecne-obchodni-podminky'
  id:
    | '__root__'
    | '/'
    | '/darkovy-poukaz'
    | '/ochrana-osobnich-udaju-gdpr'
    | '/pred-navstevou'
    | '/vseobecne-obchodni-podminky'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DarkovyPoukazRoute: typeof DarkovyPoukazRoute
  OchranaOsobnichUdajuGdprRoute: typeof OchranaOsobnichUdajuGdprRoute
  PredNavstevouRoute: typeof PredNavstevouRoute
  VseobecneObchodniPodminkyRoute: typeof VseobecneObchodniPodminkyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darkovy-poukaz': {
      id: '/darkovy-poukaz'
      path: '/darkovy-poukaz'
      fullPath: '/darkovy-poukaz'
      preLoaderRoute: typeof DarkovyPoukazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-osobnich-udaju-gdpr': {
      id: '/ochrana-osobnich-udaju-gdpr'
      path: '/ochrana-osobnich-udaju-gdpr'
      fullPath: '/ochrana-osobnich-udaju-gdpr'
      preLoaderRoute: typeof OchranaOsobnichUdajuGdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pred-navstevou': {
      id: '/pred-navstevou'
      path: '/pred-navstevou'
      fullPath: '/pred-navstevou'
      preLoaderRoute: typeof PredNavstevouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vseobecne-obchodni-podminky': {
      id: '/vseobecne-obchodni-podminky'
      path: '/vseobecne-obchodni-podminky'
      fullPath: '/vseobecne-obchodni-podminky'
      preLoaderRoute: typeof VseobecneObchodniPodminkyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DarkovyPoukazRoute: DarkovyPoukazRoute,
  OchranaOsobnichUdajuGdprRoute: OchranaOsobnichUdajuGdprRoute,
  PredNavstevouRoute: PredNavstevouRoute,
  VseobecneObchodniPodminkyRoute: VseobecneObchodniPodminkyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
